# Dockerfile
FROM node:14

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

# Instalar as dependências novamente
RUN rm -rf node_modules && npm install

# Exponha a porta que o seu aplicativo usará
EXPOSE 3001

CMD ["npm", "run", "dev"]
