default: &default
  adapter: postgresql
  encoding: utf8
  pool: 12
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: <%="#{(ENV['DATABASE_NAME'] || 'kanastra')}_development"%>

test:
  <<: *default
  database: <%="#{(ENV['DATABASE_NAME'] || 'kanastra')}_test"%>

production:
  <<: *default
  database: <%="#{(ENV['DATABASE_NAME'] || 'kanastra')}_production"%>

